### ISSUE TITLE
text_medium helper cmb2-metabox-description displays next to input instead of under

### ISSUE THREAD

**Issue by chuckreynolds** [WebDevStudios/CMB2#210]
So I'm not sure if this is intended to work this way but on  a `text` field the `cmb2-metabox-description` is a `<p class='cmb2-metabox-description">` and displays under the input just fine.
If you do at `text_medium` field however... that description helper text shows up next to the input because it renders as `<span class='cmb2-metabox-description">`

For sanity reasons I'm just making this field I'm using for phone numbers a text instead of text_medium but... If it's a bug then heads up. If it's supposed to work that way??? then I guess I'm wondering why.

Thanks. Cheers.

**Comment by jtsternberg** [comment]
There are a lot of decisions that date back to the beginning of this library, that being one of them. I believe the idea is that with smaller inputs, it's more aesthetically pleasing to have the description next to the input rather than under it. If you prefer that's not the case, you can easily add some css:
```css
.cmb-type-text-medium .cmb2-metabox-description { display: block; }
```
or even
```css
span.cmb2-metabox-description { display: block; }
```
